// EduLift notes data — Computer Science
(function() {
  if (!window.NOTES_DATA) window.NOTES_DATA = {};
  window.NOTES_DATA['Computer Science'] = {
    higher_secondary: { title: 'Higher Secondary Computer Science', sections: [
      { heading: 'Data Structures & Algorithms', content: `Arrays: fixed-size, indexed collection. O(1) access, O(n) search.\nLinked List: nodes pointing to next. O(n) access, efficient insertion.\nStack: LIFO (Last In First Out) — push/pop. Used in function calls, undo.\nQueue: FIFO (First In First Out) — enqueue/dequeue. Used in scheduling.\nTree: hierarchical structure. Binary Search Tree: left < root < right.\n\nSorting algorithms:\n• Bubble sort: O(n²) — simple, slow\n• Merge sort: O(n log n) — divide and conquer, stable\n• Quick sort: O(n log n) average, O(n²) worst\n\nBig-O notation measures time/space complexity.` },
      { heading: 'Object-Oriented Programming', content: `Four pillars of OOP:\n1. Encapsulation: bundling data + methods, hiding internal state\n2. Abstraction: showing only essential features, hiding complexity\n3. Inheritance: child class inherits properties/methods from parent class\n4. Polymorphism: same method name, different behaviour in different classes\n\nClass: blueprint for objects\nObject: instance of a class\nConstructor: special method called when object is created\nMethod overriding: child class redefines parent method` },
      { heading: 'Databases & SQL', content: `Relational databases store data in tables with rows and columns.\n\nSQL (Structured Query Language):\n• SELECT name FROM students WHERE grade = 10;\n• INSERT INTO students VALUES (1, 'Alice', 10);\n• UPDATE students SET grade = 11 WHERE id = 1;\n• DELETE FROM students WHERE id = 1;\n\nJOINs: combine data from multiple tables\nNormalisation: removes redundancy (1NF, 2NF, 3NF)\nPrimary key: unique identifier. Foreign key: references primary key of another table.` },
      { heading: 'Networking & Security', content: `OSI Model (7 layers): Physical, Data Link, Network, Transport, Session, Presentation, Application\n\nTCP/IP: Transport Control Protocol/Internet Protocol — foundation of internet\nTCP: reliable, connection-oriented (checks delivery)\nUDP: fast, connectionless (no delivery guarantee)\n\nEncryption: symmetric (same key) vs asymmetric (public/private key pair)\nHashing: one-way function (SHA-256) — cannot reverse\nFirewall: filters network traffic\nHTTPS: HTTP + TLS encryption` },
    ], quiz: [
      { q: 'Which data structure uses LIFO?', opts: ['Queue', 'Array', 'Stack', 'Linked List'], c: 2, exp: 'A Stack uses LIFO (Last In, First Out) — the last element added is the first removed. Like a stack of plates.' },
      { q: 'Big-O of merge sort?', opts: ['O(n)', 'O(n²)', 'O(n log n)', 'O(log n)'], c: 2, exp: 'Merge sort has O(n log n) time complexity in all cases (best, average, worst) — making it efficient and predictable.' },
      { q: 'Inheritance in OOP means...', opts: ['Hiding internal state', 'Child class receives properties from parent', 'Same method different behaviour', 'Showing essential features only'], c: 1, exp: 'Inheritance allows a child/subclass to inherit properties and methods from a parent/superclass, promoting code reuse.' },
      { q: 'SELECT, INSERT, UPDATE, DELETE are part of...', opts: ['Python', 'SQL', 'HTML', 'CSS'], c: 1, exp: 'These are SQL (Structured Query Language) commands for querying and manipulating relational databases.' },
      { q: 'TCP differs from UDP because TCP is...', opts: ['Faster but unreliable', 'Reliable and connection-oriented', 'Used only for streaming', 'Connectionless'], c: 1, exp: 'TCP establishes a connection and guarantees delivery (with error checking and acknowledgements). UDP is faster but does not guarantee delivery.' },
    ], extraQuizzes: [[
      { q: 'A Binary Search Tree maintains...', opts: ['Random order', 'Left < root < right', 'Alphabetical order only', 'Insertion order'], c: 1, exp: 'In a BST, the left subtree contains values less than the node, and the right subtree contains values greater — enabling O(log n) search.' },
      { q: 'Encapsulation in OOP means...', opts: ['Child inherits from parent', 'Hiding internal state and bundling data with methods', 'Same interface different implementation', 'Showing only relevant features'], c: 1, exp: 'Encapsulation bundles data (attributes) and methods that operate on the data into a class, hiding internal implementation details.' },
      { q: 'What is a foreign key?', opts: ['A unique row identifier', 'A key that references the primary key of another table', 'A key that encrypts data', 'The first column of a table'], c: 1, exp: 'A foreign key in one table references the primary key of another table, establishing relationships between tables.' },
      { q: 'Asymmetric encryption uses...', opts: ['One shared secret key', 'A public and private key pair', 'No keys', 'Three keys'], c: 1, exp: 'Asymmetric encryption uses a key pair: a public key (shared openly for encryption) and a private key (kept secret for decryption).' },
      { q: 'Polymorphism allows...', opts: ['Multiple inheritance only', 'Same method name to behave differently in different classes', 'Objects to be hidden', 'Functions to have no return value'], c: 1, exp: 'Polymorphism means "many forms" — the same method name can have different implementations in different classes (method overriding/overloading).' },
    ]]}
  };
})();
