// EduLift notes data — English
(function() {
  if (!window.NOTES_DATA) window.NOTES_DATA = {};
  window.NOTES_DATA['English'] = {
    primary:   { title: 'Primary English', sections: [
      { heading: 'Reading & Comprehension', content: `When reading, look for:\n• The main idea — what is the passage mostly about?\n• Key details — facts that support the main idea\n• Vocabulary in context — use surrounding words to guess meaning\n\nStrategies:\n1. Read the questions before the passage\n2. Highlight or underline key sentences\n3. Re-read difficult sections` },
      { heading: 'Writing Skills', content: `A good sentence has a subject and a verb: "The cat [subject] runs [verb]."\n\nTypes of sentences:\n• Statement: I like reading.\n• Question: Do you like reading?\n• Exclamation: What a great book!\n• Command: Read the next page.\n\nA paragraph has a topic sentence, supporting sentences, and a conclusion sentence.` },
      { heading: 'Grammar Basics', content: `Parts of speech:\n• Noun: person, place, thing (dog, London, happiness)\n• Verb: action or state (run, is, think)\n• Adjective: describes a noun (red, fast, tall)\n• Adverb: describes a verb, adjective, or another adverb (quickly, very, always)\n• Pronoun: replaces a noun (he, she, they, it)\n• Preposition: shows relationship (on, under, beside, between)` },
    ], quiz: [
      { q: 'Which word is a noun in: "The clever dog ran fast"?', opts: ['clever', 'ran', 'dog', 'fast'], c: 2, exp: '"Dog" is a noun — it names a living thing. "Clever" is an adjective, "ran" is a verb, "fast" is an adverb.' },
      { q: 'What type of sentence is: "What a beautiful day!"?', opts: ['Statement', 'Question', 'Command', 'Exclamation'], c: 3, exp: 'An exclamation expresses strong emotion. It starts with "What" or "How" and ends with "!". "What a beautiful day!" fits perfectly.' },
      { q: 'Which word is an adjective: "She wore a blue dress"?', opts: ['She', 'wore', 'blue', 'dress'], c: 2, exp: '"Blue" describes the noun "dress" — it is an adjective. Adjectives tell us what kind, how many, or which one.' },
      { q: 'What does a paragraph always begin with?', opts: ['A conclusion sentence', 'A topic sentence', 'A question', 'An adverb'], c: 1, exp: 'A paragraph begins with a topic sentence that introduces the main idea of that paragraph.' },
      { q: 'Identify the pronoun: "She gave him the book."', opts: ['gave', 'book', 'She', 'the'], c: 2, exp: '"She" is a pronoun — it replaces a noun (a person\'s name). "Him" is also a pronoun.' },
    ], extraQuizzes: [[
      { q: 'Which is an adverb: "She ran quickly to school"?', opts: ['She', 'ran', 'quickly', 'school'], c: 2, exp: '"Quickly" is an adverb — it describes how she ran. Most adverbs end in -ly.' },
      { q: '"The dog barked loudly." Loudly is a...', opts: ['Noun', 'Verb', 'Adjective', 'Adverb'], c: 3, exp: '"Loudly" describes how the dog barked — it modifies the verb "barked", so it\'s an adverb.' },
      { q: 'Which sentence has correct punctuation?', opts: ['she went to the shop', 'She went to the shop.', 'she went to the shop.', 'She went to the shop'], c: 1, exp: 'A correct sentence starts with a capital letter and ends with a full stop, question mark, or exclamation mark.' },
      { q: 'What is the main idea of a paragraph?', opts: ['The final sentence', 'The topic sentence', 'The longest sentence', 'The adjectives used'], c: 1, exp: 'The topic sentence, usually the first sentence, states the main idea of the paragraph.' },
      { q: 'Which word is a preposition: "The cat sat under the table"?', opts: ['cat', 'sat', 'under', 'table'], c: 2, exp: '"Under" is a preposition — it shows the relationship (position) between the cat and the table.' },
    ]]},
    secondary: { title: 'Secondary English', sections: [
      { heading: 'Literature & Analysis', content: `When analysing a text, use PEE structure:\n• Point: make your argument\n• Evidence: quote from the text\n• Explanation: explain how the evidence supports your point\n\nLiterary devices:\n• Simile: comparison using "like" or "as" — "brave as a lion"\n• Metaphor: direct comparison — "Life is a journey"\n• Personification: giving human qualities to non-human things\n• Alliteration: repetition of consonant sounds — "Peter Piper picked"` },
      { heading: 'Grammar & Composition', content: `Tenses:\n• Simple present: She writes. Simple past: She wrote. Future: She will write.\n• Present continuous: She is writing. Past continuous: She was writing.\n• Present perfect: She has written. Past perfect: She had written.\n\nActive vs. Passive:\nActive: "The teacher marked the paper."\nPassive: "The paper was marked by the teacher."\nPassive is used when the action is more important than the actor.` },
      { heading: 'Essay Writing', content: `Essay structure:\n1. Introduction: hook + thesis statement (your main argument)\n2. Body paragraphs: each begins with a topic sentence + evidence + analysis\n3. Conclusion: restate thesis + summary of key points + broader significance\n\nParagraphs should be linked with connectives:\n• Addition: furthermore, moreover, in addition\n• Contrast: however, on the other hand, nevertheless\n• Conclusion: therefore, consequently, as a result` },
    ], quiz: [
      { q: '"Life is a roller coaster" is an example of...', opts: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], c: 1, exp: 'A metaphor makes a direct comparison without using "like" or "as". Life IS a roller coaster — direct equation.' },
      { q: 'PEE stands for...', opts: ['Point, Evidence, Explanation', 'Paragraph, Evidence, Example', 'Point, Example, Evaluate', 'Proof, Evidence, Explain'], c: 0, exp: 'PEE = Point (your argument), Evidence (quote/reference), Explanation (how the evidence supports your point).' },
      { q: 'Which is in passive voice?', opts: ['She wrote the letter', 'The letter was written by her', 'She is writing', 'She has written'], c: 1, exp: 'Passive: subject receives the action. "The letter was written by her" — the letter is the subject but receives the action.' },
      { q: 'Which connective shows contrast?', opts: ['Furthermore', 'Therefore', 'However', 'Similarly'], c: 2, exp: '"However" introduces a contrasting point. "Furthermore" adds information, "Therefore" shows result, "Similarly" shows comparison.' },
      { q: '"Peter Piper picked peppers" is an example of...', opts: ['Metaphor', 'Alliteration', 'Assonance', 'Onomatopoeia'], c: 1, exp: 'Alliteration is the repetition of the same consonant sound at the start of nearby words. "P" is repeated here.' },
    ], extraQuizzes: [[
      { q: 'What is the purpose of a thesis statement?', opts: ['To summarise the text', 'To state the main argument of the essay', 'To introduce evidence', 'To conclude the essay'], c: 1, exp: 'The thesis statement presents the main argument/position of the essay. It usually appears at the end of the introduction.' },
      { q: '"The stars danced in the sky" is...', opts: ['Simile', 'Metaphor', 'Personification', 'Hyperbole'], c: 2, exp: 'Personification gives human qualities (dancing) to non-human things (stars). Stars cannot literally dance.' },
      { q: 'Present perfect tense of "write" is...', opts: ['She wrote', 'She has written', 'She was writing', 'She writes'], c: 1, exp: 'Present perfect: has/have + past participle. "She has written" — the action is completed with relevance to the present.' },
      { q: 'Which is the best topic sentence for a paragraph about climate change?', opts: ['Climate change is bad.', 'Climate change is a pressing global crisis requiring immediate action.', 'There are many things about climate change.', 'Scientists study climate change.'], c: 1, exp: 'A good topic sentence is specific and states a clear point. Option B is specific, arguable, and introduces the paragraph\'s focus.' },
      { q: '"She is as brave as a lion." This is a...', opts: ['Metaphor', 'Personification', 'Simile', 'Hyperbole'], c: 2, exp: 'A simile uses "like" or "as" to compare two things. "As brave AS a lion" — comparison using "as".' },
    ]]},
    higher_secondary: { title: 'Higher Secondary English', sections: [
      { heading: 'Literary Theory', content: `Key literary theories:\n\nNew Criticism: focus on the text itself — close reading, imagery, ambiguity\nMarxist criticism: examines class struggle and power in texts\nFeminist criticism: examines gender roles and representation\nPost-colonial theory: examines effects of colonialism in literature\n\nAuthor's purpose: inform, persuade, entertain, describe\nContext matters: historical, social, cultural background of a text shapes its meaning.` },
      { heading: 'Advanced Grammar', content: `Subjunctive mood: used for hypothetical or wished-for situations.\n"If I were you..." (not "was") — subjunctive of "to be"\n"I suggest he study harder." (not "studies")\n\nParticipial phrases: "Having finished the exam, she left."\nAbsolute constructions: "The work done, he rested."\n\nAnaphor: repeating a phrase at the start of clauses for effect — "I have a dream..."\nEpistrophe: repetition at end of clauses — "government of the people, by the people, for the people"` },
      { heading: 'Critical Writing', content: `Argue with nuance — acknowledge counterarguments:\n"While some argue X, the evidence suggests Y because..."\n\nHedging language: "This suggests...", "It could be argued...", "The evidence implies..."\n\nAnalyse language choices: why did the author choose this word/structure?\n\nIntertextuality: references to other texts within a text. Allusion: indirect reference.\n\nThe death of the author (Barthes): once published, the author\'s intentions are irrelevant — the reader creates meaning.` },
    ], quiz: [
      { q: 'Which critical theory examines gender representation?', opts: ['Marxist', 'Feminist', 'New Criticism', 'Post-colonial'], c: 1, exp: 'Feminist literary criticism examines how gender, sexuality, and power are represented in texts and challenges patriarchal viewpoints.' },
      { q: 'The subjunctive is used in which sentence?', opts: ['She was tired', 'If I were a bird', 'They are happy', 'He runs fast'], c: 1, exp: '"If I were a bird" uses the subjunctive mood — "were" (not "was") indicates a hypothetical/contrary-to-fact condition.' },
      { q: 'Repetition at the beginning of clauses is called...', opts: ['Epistrophe', 'Anaphora', 'Chiasmus', 'Asyndeton'], c: 1, exp: 'Anaphora = repetition at the START of successive clauses. E.g. "I have a dream...I have a dream..." (MLK).' },
      { q: 'Barthes\' "Death of the Author" argues that...', opts: ['Authors should not write ambiguously', 'Meaning is created by the reader, not the author', 'Authors control all meaning', 'Literature has no meaning'], c: 1, exp: 'Barthes argued that once a text is published, the author\'s intended meaning is irrelevant. The reader creates meaning through their interpretation.' },
      { q: 'Intertextuality refers to...', opts: ['Analysing a single text', 'References to other texts within a text', 'The author\'s biography', 'Grammar structures'], c: 1, exp: 'Intertextuality is the relationship between texts — how a text references, quotes, or is shaped by other texts.' },
    ], extraQuizzes: [[
      { q: 'Post-colonial criticism examines...', opts: ['Gender roles in text', 'Economic class in literature', 'Effects of colonialism in literature', 'Formalist text analysis'], c: 2, exp: 'Post-colonial theory examines how colonialism and its legacy are represented in literature, often questioning Eurocentric perspectives.' },
      { q: '"The work done, they rested" is a(n)...', opts: ['Participial phrase', 'Absolute construction', 'Subjunctive clause', 'Anaphora'], c: 1, exp: 'An absolute construction (or nominative absolute) is a phrase with a subject and participial verb that is grammatically independent of the main clause.' },
      { q: 'Hedging language is used to...', opts: ['Make strong claims', 'Express certainty', 'Acknowledge uncertainty and qualify claims', 'Introduce evidence'], c: 2, exp: 'Hedging language (e.g. "it could be argued", "this suggests") qualifies claims and shows academic caution.' },
      { q: 'New Criticism focuses on...', opts: ['Author\'s biography', 'Historical context', 'The text itself through close reading', 'Class struggle'], c: 2, exp: 'New Criticism (formalism) argues for close reading of the text itself, ignoring author biography and historical context (intentional fallacy).' },
      { q: 'Repetition at the END of successive clauses is...', opts: ['Anaphora', 'Epistrophe', 'Alliteration', 'Assonance'], c: 1, exp: 'Epistrophe = repetition at the END of successive clauses. E.g. "government of the people, by the people, for the people."' },
    ]]}
  };
})();
